backend:
  name: git-gateway
  branch: main

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "site/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Bits and Pieces", name: "bits_and_pieces", widget: "boolean", default: true, required: false}
      - {label: "Header Image Left", name: "header_left", widget: "image", required: false}
      - {label: "Header Image Right", name: "header_right", widget: "image", required: false}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "Redirect Rules"
        name: "redirects"
        file: "site/static/_redirects"
        editor:
          { preview : "false" }
        fields:
          - label: "Redirects"
            name: "redirects"
            widget: "list"
            fields:
              - { label: "From", name: "from", widget: "string" }
              - { label: "To", name: "to", widget: "string" }
              - label: "Status"
                name: "status"
                widget: "select"
                options:
                  - { label: "Permanent Redirect (301)", value: 301 }
                  - { label: "Temporary Redirect (302)", value: 302 }
                  - { label: "See Other (303)", value: 303 }
                  - { label: "Not Modified (304)", value: 304 }
